CREATE TABLE sh_ml_contatoPropriedade (

	id				CHAR(36) 		NOT NULL,
	idPropriedade	CHAR(36) 		NOT NULL,
	valor			VARCHAR(32) 	NOT NULL,
	
	CONSTRAINT SH_ML_PROPRIEDADE_PK PRIMARY KEY (id),
	CONSTRAINT SH_ML_CONTATOPROPRIEDADE_PROPRIEDADE_FK FOREIGN KEY (idPropriedade) REFERENCES sh_ml_propriedade(id) 

) ENGINE=InnoDB DEFAULT CHARSET=utf8;
