CREATE TABLE sh_ml_email (

	id 					CHAR(36) NOT NULL,
	nome				VARCHAR(128) NOT NULL,
	email				VARCHAR(128) NOT NULL,
	provedor			VARCHAR(128) NOT NULL,
	info				TEXT NULL,
	
	CONSTRAINT SH_ML_EMAIL_PK PRIMARY KEY (id),
	CONSTRAINT SH_ML_EMAIL_UNIQUE UNIQUE (email)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;