CREATE TABLE sh_contatoDestino (

	id				CHAR(36) 		NOT NULL,
	nome			VARCHAR(128) 	NOT NULL,
	email			VARCHAR(128)	NOT NULL,
	alias			VARCHAR(128)	NOT NULL,
	
	CONSTRAINT SH_CONTATODESTINO_PK PRIMARY KEY (id),
	CONSTRAINT SH_CONTATODESTINO_EMAIL_UNIQUE UNIQUE (email),
	CONSTRAINT SH_CONTATODESTINO_ALIAS_UNIQUE UNIQUE (alias)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX SH_CONTATODESTINO_ALIAS ON sh_contatoDestino(alias);

CREATE TABLE sh_contato (

	id				CHAR(36) 		NOT NULL,
	idDestino		CHAR(36) 		NOT NULL,
	localizador		VARCHAR(32) 	NOT NULL,
	nome			VARCHAR(128) 	NOT NULL,
	telefone		VARCHAR(24)		NULL,
	email			VARCHAR(256)	NOT NULL,
	idCidade		CHAR(36)		NULL,
	idEstado		CHAR(36) 		NULL,
	assunto			VARCHAR(128)	NULL,
	mensagem		TEXT			NOT NULL,
	enviadoEm		DATETIME		NOT NULL,
	ip				VARCHAR(32)		NOT NULL,
	arquivado		INTEGER			NOT NULL DEFAULT 2,
	
	CONSTRAINT SH_CONTATO_PK PRIMARY KEY (id),
	CONSTRAINT SH_CONTATO_DESTINO_FK FOREIGN KEY (idDestino) REFERENCES sh_contatoDestino(id),
	CONSTRAINT SH_CONTATO_CIDADE_FK FOREIGN KEY (idCidade) REFERENCES ibge_localidadeCidade(id),
	CONSTRAINT SH_CONTATO_ESTADO_FK FOREIGN KEY (idEstado) REFERENCES ibge_localidadeEstado(id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE sh_contatoDestino ADD COLUMN removivel INTEGER NOT NULL DEFAULT 1;
INSERT INTO sh_contatoDestino VALUES ('849580E4-BED4-4002-BDD8-91F82DEB291E', 'Padrão', 'contato@bgstudios.com.br', 'default', 2);

ALTER TABLE sh_contato ADD COLUMN enviado INTEGER NOT NULL DEFAULT 2;