CREATE TABLE sh_blogCategoria (
	id				CHAR(36) NOT NULL,
	titulo			VARCHAR(128) NOT NULL,
	descricao		VARCHAR(1024) NULL,
	posicao		INT NOT NULL DEFAULT 0,
	
	CONSTRAINT SH_BLOGCATEGORIA_PK PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sh_blog (

	id				CHAR(36) NOT NULL,
	idCategoria		CHAR(36) NULL,
	titulo			VARCHAR(128) NOT NULL,
	chamada			VARCHAR(1024) NULL,
	conteudo		TEXT NOT NULL,
	data			DATE NOT NULL,
	keywords		VARCHAR(256) NULL,
	autor			VARCHAR(128) NULL,
	
	CONSTRAINT SH_BLOG_PK PRIMARY KEY (id),
	CONSTRAINT SH_BLOG_CATEGORIA_FK FOREIGN KEY (idCategoria) REFERENCES sh_blogCategoria(id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;