CREATE TABLE sh_token (
	id				CHAR(36)		NOT NULL,
	status			INT 			NOT NULL,
	geradoEm		DATETIME 		NOT NULL,
	finalizadoEm	DATETIME 		NULL,
	security		VARCHAR(128 )	NULL,
	
	CONSTRAINT SH_TOKEN_PK PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE INDEX SH_TOKEN_STATUS ON sh_token(status);