CREATE TABLE sh_imageRepository (

	id 					CHAR(36) 		NOT NULL,
	idContent			CHAR(36) 		NOT NULL,
	idDataSource		VARCHAR(128) 	NOT NULL,
	idCapa				CHAR(36) 		NULL,
	legenda				VARCHAR(1024) 	NULL,
	quantidade			INTEGER 		NOT NULL DEFAULT 0,

	CONSTRAINT SH_IMAGEREPOSITORY_PK PRIMARY KEY (id),
	CONSTRAINT SH_IMAGEREPOSITORY_UNIQUE UNIQUE (idContent, idDataSource)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sh_imageRepositoryPicture (

	id 					CHAR(36) 		NOT NULL,
	idRepository		CHAR(36) 		NOT NULL,
	idPicture			CHAR(36)		NOT NULL,
	idProximo 			CHAR(36) 		NULL,
	legenda				VARCHAR(1024)	NULL,
	primeiro			INT				NOT NULL DEFAULT 2,
	
	CONSTRAINT SH_IMAGEREPOSITORYPICTURE_PK 				PRIMARY KEY (id),
	CONSTRAINT SH_IMAGEREPOSITORYPICTURE_REPOSITORY_FK 		FOREIGN KEY (idRepository) 	REFERENCES sh_imageRepository(id),
	CONSTRAINT SH_IMAGEREPOSITORYPICTURE_PICTURE_FK 		FOREIGN KEY (idPicture) 	REFERENCES sh_filePicture(id),
	CONSTRAINT SH_IMAGEREPOSITORYPICTURE_PROXIMO_FK 		FOREIGN KEY (idProximo) 	REFERENCES sh_imageRepositoryPicture(id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE sh_imageRepository ADD CONSTRAINT SH_IMAGEREPOSITORY_CAPA_FK FOREIGN KEY (idCapa) REFERENCES sh_imageRepositoryPicture(id);

CREATE TABLE sh_imageRepositoryViewed (

	id				CHAR(36) NOT NULL,
	idRepository	CHAR(36) NOT NULL,
	idProfile		CHAR(36) NOT NULL,
	times			INT NOT NULL DEFAULT 0,
	
	CONSTRAINT SH_IMAGEREPOSITORYVIEWED_PK PRIMARY KEY (id),
	CONSTRAINT SH_IMAGEREPOSITORYVIEWED_REPOSITORY_FK FOREIGN KEY (idRepository) REFERENCES sh_imageRepository(id),
	CONSTRAINT SH_IMAGEREPOSITORYVIEWED_PROFILE_FK FOREIGN KEY (idProfile) REFERENCES sh_userProfile (id),
	CONSTRAINT SH_IMAGEREPOSITORYVIEWED_UNIQUE_REP_PROFILE UNIQUE (idRepository, idProfile)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;