CREATE TABLE sh_userProfile (
	
	id				VARCHAR(36) NOT NULL,
	alias			VARCHAR(128) NOT NULL,
	nome			VARCHAR(128) NOT NULL,
	descricao		VARCHAR(1024) NULL,
	renderPath		VARCHAR(128) NOT NULL,
	
	CONSTRAINT SH_USERPROFILE_PK PRIMARY KEY (id),
	CONSTRAINT SH_USERPROFILE_ALIAS UNIQUE(alias)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sh_user (
	id					VARCHAR(36) NOT NULL,
	defaultProfile 		VARCHAR(36) NULL
	nome				VARCHAR(256) NOT NULL,
	email				VARCHAR(128) NOT NULL,
	login				VARCHAR(128) NOT NULL,
	password			VARCHAR(256) NOT NULL,
	habilitado			INT NOT NULL,
	multiSecao			INT NOT NULL,
	
	CONSTRAINT SH_USER_PK PRIMARY KEY (id),
	CONSTRAINT SH_USER_EMAIL_UNIQUE UNIQUE (email),
	CONSTRAINT SH_USER_LOGIN_UNIQUE UNIQUE (login),
	CONSTRAINT SH_USER_DEFAULTPROFILE_FK FOREIGN KEY (defaultProfile) REFERENCES sh_userProfile(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sh_userProfileUser (
	
	id				VARCHAR(36) NOT NULL,
	idUser			VARCHAR(36) NOT NULL,
	idProfile		VARCHAR(36) NOT NULL,
	
	CONSTRAINT SH_USERPROFILEUSER_PK PRIMARY KEY (id),
	CONSTRAINT SH_USERPROFILEUSER_USER_FK FOREIGN KEY (idUser) REFERENCES sh_user(id),
	CONSTRAINT SH_USERPROFILEUSER_PROFILE_FK FOREIGN KEY (idProfile) REFERENCES sh_userProfile(id)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE UNIQUE INDEX SH_USERPROFILEUSER_USER_PROFILE_UNIQUE ON sh_userProfileUser(idUser, idProfile);

-- 2014.06.05
ALTER TABLE sh_userProfileUser ADD COLUMN dataInicio DATE NOT NULL DEFAULT '2014-01-01';
ALTER TABLE sh_userProfileUser ADD COLUMN dataFim DATE NULL;
ALTER TABLE sh_userProfileUser ADD COLUMN ativo INT NOT NULL DEFAULT 3 COMMENT '1->ATIVO, 2->ENCERRADO, 3->AGUARDANDO';

-- 2014.06.06
ALTER TABLE sh_user CHANGE email email VARCHAR(128) NULL;
ALTER TABLE sh_user ADD COLUMN changePassNextLogin INT NOT NULL DEFAULT 2;
INSERT INTO sh_userProfile VALUES ('F291FE30-9171-4703-AD5F-6872BA7B65B7', 'sheer.loginChangePassword', 'Sheer - Change Password on login', NULL, 'sheer/loginChangePassword');

-- 2014.06.09
CREATE TABLE sh_userLoggedIn (
	idUser				VARCHAR(36) NOT NULL,
	loggedAt 			DATETIME NOT NULL,
	userAgent			VARCHAR(256) NOT NULL,
	userIp				VARCHAR(64) NOT NULL,
	sessionId			VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 14.09.10
ALTER TABLE sh_userProfile ADD COLUMN guestProfile INT NOT NULL DEFAULT 2 AFTER descricao;























