-- 2014.09.01
CREATE TABLE sh_userFacebook (
	id				CHAR(36) 		NOT NULL,
	fbId			VARCHAR(36) 	NOT NULL,
	sheerId			CHAR(36) 		NULL,
	nome			VARCHAR(128) 	NOT NULL,
	email			VARCHAR(128)	NOT NULL,
	username		VARCHAR(128) 	NOT NULL,
	nascimento		DATE 			NULL,
	sexo			CHAR(1) 		NULL,
	foto			CHAR(36) 		NULL,
	link			VARCHAR(256) 	NULL,
	fbUpdated		DATETIME		NULL,
	
	CONSTRAINT SH_USERFACEBOOK_PK PRIMARY KEY (id),
	CONSTRAINT SH_USERFACEBOOK_SHEERID_FK FOREIGN KEY (sheerId) REFERENCES sh_user(id),
	CONSTRAINT SH_USERFACEBOOK_FBID_UNIQUE UNIQUE (fbId),
	CONSTRAINT SH_USERFACEBOOK_SHEERID_UNIQUE UNIQUE (sheerId)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE sh_userFacebookAccessToken (
	id				CHAR(36) 		NOT NULL,
	fbId			VARCHAR(36) 	NOT NULL,
	accessToken		VARCHAR(256) 	NOT	NULL,
	machineId		VARCHAR(128) 	NULL,
	expiresAt		DATETIME 		NOT NULL,
	createdAt		DATETIME 		NOT NULL,
	
	CONSTRAINT SH_USERFACEBOOKACCESSTOKEN_PK PRIMARY KEY (id),
	CONSTRAINT SH_USERFACEBOOKACCESSTOKEN_FBUSER_FK FOREIGN KEY (fbId) REFERENCES sh_userFacebook(fbId)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 14.09.12
RENAME TABLE sh_userFacebook TO sh_social_facebook;
RENAME TABLE sh_userFacebookAccessToken TO sh_social_facebookAccessToken;