CREATE TABLE sh_ml_contato (

	id 					CHAR(36) NOT NULL,
	nome				VARCHAR(128) NULL,
	email				VARCHAR(128) NOT NULL,
	
	CONSTRAINT SH_ML_CONTATO_PK PRIMARY KEY (id),
	CONSTRAINT SH_ML_CONTATO_UNIQUE UNIQUE (email)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;