CREATE TABLE bg_clientePessoa(

	id				CHAR(36) NOT NULL,
	idCliente		CHAR(36) NOT NULL,
	idPessoa		CHAR(36) NOT NULL,
	idDepartamento	CHAR(36) NOT NULL,
	
	CONSTRAINT BG_CLIENTEPESSOA_PK PRIMARY KEY (id),
	
	CONSTRAINT BG_CLIENTEPESSOA_PESSOA_FK FOREIGN KEY (idCliente) REFERENCES bg_cliente(id),
	CONSTRAINT BG_CLIENTEPESSOA_DEPARTAMENTO_FK FOREIGN KEY (idDepartamento) REFERENCES bg_pessoaDepartamento (id)

)ENGINE=InnoDB DEFAULT CHARSET=utf8;