CREATE TABLE sh_ml_envioTeste(

	id 						CHAR(36)NOT NULL,
	idCampanha				CHAR(36)NOT NULL,
	idRemetente				VARCHAR(128) NOT NULL,
	assunto					VARCHAR(128) NOT NULL,
	html					TEXT NOT NULL,
	destinos				TEXT NOT NULL,
	envioEm					DATETIME NOT NULL,
	envioPor				CHAR(36) NOT NULL,
	
	CONSTRAINT SH_ML_ENVIOTESTE PRIMARY KEY (id),
	CONSTRAINT SH_ML_ENVIOTESTE_CAMPANHA_FK FOREIGN KEY (idCampanha) REFERENCES sh_ml_campanha (id),
	CONSTRAINT SH_ML_ENVIOTESTE_REMETENTE_FK FOREIGN KEY (idRemetente) REFERENCES sh_ml_remetente (id)
	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;