CREATE TABLE sh_role (

	id				VARCHAR(36) NOT NULL,
	alias			VARCHAR(128) NOT NULL,
	description		VARCHAR(1024) NULL,
	
	CONSTRAINT SH_ROLE_PK PRIMARY KEY (id),
	CONSTRAINT SH_ROLE_ALIAS_UNIQUE UNIQUE (alias)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;