CREATE TABLE sh_ml_listaImportacao(

	id					CHAR(36) NOT NULL,
	idLista				CHAR(36) NOT NULL,
	importadoEm 		DATETIME NOT NULL,
	importadoPor 		CHAR(36) NOT NULL,
	total				INTEGER NOT NULL,
	novos				INTEGER NOT NULL,
	atualizados			INTEGER NOT NULL,
	ativar				INTEGER NOT NULL,
	arquivo				CHAR(36) NOT NULL,
	
	CONSTRAINT SH_ML_LISTAIMPORTACAO_PK PRIMARY KEY (id),
	CONSTRAINT SH_ML_LISTAEIMPORTACAO_LISTA FOREIGN KEY (idLista) REFERENCES sh_ml_lista (id)
	
)ENGINE=InnoDB DEFAULT CHARSET=utf8;